export const EMAIL_VERIFICATION_OTP_LENGTH = 6;
export const EMAIL_VERIFICATION_OTP_EXPIRY_MINUTES = 10;
export const EMAIL_VERIFICATION_OTP_RESEND_COOLDOWN_SECONDS = 60;
export const EMAIL_VERIFICATION_OTP_MAX_ATTEMPTS = 5;
export const PASSWORD_RESET_OTP_EXPIRY_MINUTES = 10;
export const PASSWORD_RESET_OTP_RESEND_COOLDOWN_SECONDS = 60;
export const PASSWORD_RESET_OTP_MAX_ATTEMPTS = 5;
