declare const nodeEnvironments: readonly ["development", "test", "production"];
declare const logLevels: readonly ["fatal", "error", "warn", "info", "debug", "trace"];
declare const referralRewardTypes: readonly ["PERCENTAGE", "FIXED_AMOUNT"];
declare const databaseSslModes: readonly ["disable", "allow", "prefer", "require", "verify-ca", "verify-full", "no-verify"];
type NodeEnv = (typeof nodeEnvironments)[number];
type LogLevel = (typeof logLevels)[number];
type ReferralRewardType = (typeof referralRewardTypes)[number];
type DatabaseSslMode = (typeof databaseSslModes)[number];
export type ValidatedEnvironment = {
    NODE_ENV: NodeEnv;
    PORT: string;
    API_PREFIX: string;
    LOG_LEVEL: LogLevel;
    DATABASE_URL: string;
    DATABASE_SSL_MODE?: DatabaseSslMode | '';
    PRISMA_QUERY_TIMEOUT_MS: string;
    APP_PUBLIC_URL: string;
    APP_PLATFORM_URL: string;
    BRAND_LOGO_PATH: string;
    BRAND_NAME: string;
    SUPPORT_EMAIL: string;
    BREVO_API_KEY: string;
    BREVO_SENDER_NAME: string;
    BREVO_SENDER_EMAIL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_ACCESS_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    CORS_ALLOWED_ORIGINS: string;
    CORS_CREDENTIALS: string;
    THROTTLE_TTL: string;
    THROTTLE_LIMIT: string;
    REDIS_HOST: string;
    REDIS_PORT: string;
    REDIS_DB: string;
    REDIS_TLS: string;
    REDIS_USERNAME?: string;
    REDIS_PASSWORD?: string;
    AWS_REGION?: string;
    AWS_S3_BUCKET_NAME?: string;
    AWS_ACCESS_KEY_ID?: string;
    AWS_SECRET_ACCESS_KEY?: string;
    AWS_S3_ENDPOINT?: string;
    AWS_S3_FORCE_PATH_STYLE?: string;
    CLOUDFRONT_DOMAIN?: string;
    CLOUDFRONT_KEY_PAIR_ID?: string;
    CLOUDFRONT_PRIVATE_KEY?: string;
    FAWRY_BASE_URL?: string;
    FAWRY_MERCHANT_CODE?: string;
    FAWRY_SECURITY_KEY?: string;
    FAWRY_RETURN_URL?: string;
    FAWRY_NOTIFICATION_URL?: string;
    PAYPAL_CLIENT_ID?: string;
    PAYPAL_CLIENT_SECRET?: string;
    PAYPAL_BASE_URL?: string;
    PAYPAL_WEBHOOK_ID?: string;
    REFERRAL_REWARD_TYPE: ReferralRewardType;
    REFERRAL_REWARD_VALUE: string;
    REFERRAL_COUPON_EXPIRES_DAYS: string;
};
export declare function validateEnv(config: Record<string, unknown>): ValidatedEnvironment;
export {};
